USE [Decideify];
GO

set identity_insert [UserProfile] on
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (1, 'Lil Coolin', 'thistbh', 'Coolin', 'Matteson', 'coolin@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (2, 'LoganVM', 'thistbh', 'Logan', 'Van Meter', 'logan@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (3, 'BeanTeamHan', 'thistbh', 'Hannah', 'Thompson', 'hannah@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (4, 'DarrinPD', 'thistbh', 'Darrin', 'Daugherty', 'darrin@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (5, 'AndyMan', 'thistbh', 'Andy', 'Hanks', 'andy@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (6, 'A-Nya aka Mizz Chief', 'thistbh', 'A-Nya', 'Badger', 'a-nya@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (7, 'Ohio Chelsea', 'thistbh', 'Chelsea', 'Hamlin', 'chelsea@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (8, 'Christian', 'thistbh', 'Christian', 'Montoya', 'christian@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (9, 'Mariia', 'thistbh', 'Mariia', 'Porplenko', 'mariia@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (10, 'Call me Cal', 'thistbh', 'Caleen', 'Boyter', 'cal@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (11, 'Woody aka Big Trollin', 'thistbh', 'Norwood', 'Henderson', 'norwood@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (12, 'Kari', 'thistbh', 'Kari', 'Rehe', 'kari@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (13, 'Juan', 'thistbh', 'Juan', 'Alcalde', 'juan@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (14, 'Max', 'thistbh', 'Max', 'Aguilar', 'max@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (15, 'Tommy the Coding Swami', 'thistbh', 'Tommy', 'Spurlock', 'tommy@gmail.com', '1900-01-01', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (16, 'Sarah (hates compliments)', 'thistbh', 'Sarah', 'Brooks or something', 'sarah@gmail.com', '1903-01-01', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
insert into UserProfile (Id, Username, [Password], FirstName, LastName, Email, CreateDateTime, ImageLocation, IsPublic, Bio) values (17, 'Barry The Kid Griffey Jr.', 'thistbh', 'Barry', 'Griffith', 'barry@gmail.com', '2023-08-28', 'https://robohash.org/numquamutut.png?size=150x150&set=set1', 'true', '');
set identity_insert [UserProfile] off